### ISSUE TITLE
Clarify default data directory for `mega`

### ISSUE THREAD

**Issue by MrBeanCpp** [moxin-org/moly#148]
I'm working on the integration of `mega` and `moxin`. see PR #147 
I need to determine the appropriate directory for storing mega data, which includes:
- log
- database (SQLite)
- cache
- ...

By default, `mega` data directory is `/tmp/.mega`.

I noticed these two directories: 
- `~/.local/share/moxin`
- `~/.config/moxin`

Should I use these directories, or is there a more appropriate location for mega data? Any guidance would be appreciated.

**Comment by joulei** [comment]
I believe this has been solved in #147
