### ISSUE TITLE
The "stop streaming" button does not work properly if clicked before streaming starts

### ISSUE THREAD

**Issue by kevinaboos** [moxin-org/moly#206]
If the user clicks the "stop" button (in the prompt text input box) _before_ any streaming output is actually received back by Moxin, then it will permanently freeze the app. 

see screenshot below -- I clicked the stop button before anything actually started streaming back from the model, and it results in the app being permanently stuck in this state. 

![image](https://github.com/user-attachments/assets/cde5ce87-e3aa-442a-a440-4cad0daeae1d)

------------

An "easy" fix would be to disable the stop button until streaming begins. But on slower machines (and/or larger models), it can take multiple _minutes_ for the model to send the first streaming output buffer back, so that solution is not ideal because the user has no option but to helplessly wait until the model actually generates something (which defeats the entire benefit of a stop button, imo).

**Comment by jmbejar** [comment]
Part of this issue was addressed by #246, but we're aware the backend has a limitation where it is not possible to interrupt the chat generation before the streaming has started. We will have a bit more robust code around the cancellation when the integration with Mae is completed.

**Comment by noxware** [comment]
Currently, it should not freeze the whole app but it seems like the stop button doesn't work until something is streamed back. The linked PR should fix that. You can test it if you want.

**Comment by kevinaboos** [comment]
Feel free to close the issue if it's been fixed. I don't have the bandwidth to test it thoroughly enough myself.

**Comment by noxware** [comment]
No worries, notifying you just in case. Will proceed like that then 🙌
