### ISSUE TITLE
"Resume Chat" is only shown for one model -- only the model most recently used.

### ISSUE THREAD

**Issue by kevinaboos** [moxin-org/moly#209]
## Current behavior
This is confusing, as it makes it seem like the user has not actually started prior chats with any other model besides the most-recently used one.

The screenshot below shows that only the last model has the `Resume Chat` button shown, when in reality the "Chat" screen shows that **there are existing chats with all three models**.
![image](https://github.com/user-attachments/assets/37f8411f-e583-49b0-846e-16eff8bc444c)

## Expected behavior
I would expect that the "My Models" screen show the "Resume Chat" button for *all* models that have at least one chat open. And then, when the user clicks on "Resume Chat", it takes you to the chat panel where that model was most recently used. 

Alternatively, clicking "Resume Chat" could bring up a dropdown menu that shows all the chats started with that model, but that is more complex (and perhaps _too_ complicated for a simple chat app).

**Comment by jmbejar** [comment]
We have recently removed the "Resume Chat" button from this screen, after some changes in the manner we change and load models from the chat screen. Looks like a not longer relevant issue, so we may want to close the issue.
