### ISSUE TITLE
Improve how text streaming is displayed

### ISSUE THREAD

**Issue by joulei** [moxin-org/moly#255]
## Problem
Currently the text streaming looks quite choppy compared to other LM platforms. The text is not displayed evenly or at a consistent pace, which makes the UI look janky.

Compare how the text is displayed in different apps:

**Claude**
The text is displayed line by line, with the Claude icon at the bottom simulating a cursor.

https://github.com/user-attachments/assets/d73e2b64-1e71-4da7-af50-af0c355d3a42

**ChatGPT (desktop)**
The text seems to be _mostly_ displayed word by word, with a "rounded cursor" at the current end of text.

https://github.com/user-attachments/assets/09b11f82-b6fb-4c01-8ade-07ce3cefb6f7

**Moxin**

Different-sized blocks of text are displayed at different speeds. This might not look as bad on this video, but it feels a lot worse on slower hardware.

https://github.com/user-attachments/assets/e2d20b47-abd3-49df-bbeb-01c315c5feaf

## Proposed fix
We could take inspiration from other LM tools and implement some pacing that makes the text be displayed more evenly. We could do this either line by line like Claude, word by word (ChatGPT), or some other way that introduces consistency.
Adding some type of cursor indication at the end of the text seems like a good idea to make clear that text is being streamed. This could also help with the issue described in https://github.com/moxin-org/moxin/issues/199. This could be something simple like temporarily adding a special character like the ChatGPT “●” (U+25CF) at the end of the text until the streaming has finished. Or it could be a separate icon beneath the text like in Claude (it could also be animated). 

## Notes
Issue https://github.com/moxin-org/moxin/issues/199 describes how to look for when the model has finished streaming. Also there mechanisms in place already being used to hide the "Stop Streaming" button once streaming has finished.

**Comment by Guocork** [comment]
I am currently facing an issue with how to select the AI's ongoing reply for caching the message content. At present, Moxin renders all the messages in the store at once for the `chat_line` rendering. In this case, determining how to select the AI's current reply in the conversation with the user becomes a challenge. So far, I haven't found a corresponding solution."
[This is the set_text function](https://github.com/moxin-org/moxin/blob/main/src/chat/chat_line.rs#L418-L445)
[This is the render function](https://github.com/moxin-org/moxin/blob/8328c77e53c91fa08c90de067254074d3b120df7/src/chat/chat_panel.rs#L885)

**Comment by joulei** [comment]
@Guocork besides our offline conversations, I think a good starting point could be to add a character (e.g. ●) simulating the cursor at the end of the message (while streaming). If you're struggling with controlling how the text is updated on the screen, this could be a starting point that will make you identify when and and where to update the message content (`ChatLine` - `draw_walk()`), and also it'll require you to pass a flag from `ChatPanel` to `ChatLine` indicating wether that's the end of the stream or if there's more text incoming.

With that implemented we can check if pacing the text display is necessary or not.

**Comment by Guocork** [comment]
I fix that in pr #262

**Comment by joulei** [comment]
For the time being we'll close this with the improvement in #262
