### ISSUE TITLE
Chat messages should use a consistent font

### ISSUE THREAD

**Issue by joulei** [moxin-org/moly#263]
It seems like different message types (plain_text vs markdown) are using different fonts.
We should make sure that the same font is used for all message types, when it comes to non-code text. This probably requires to override the font used by the Markdown widget, to match the font used by Moxin elsewhere (GoNoto variations).
Do not override Markdown's `draw_fixed`, because `draw_fixed` is used for rendering code blocks which require a monospace font.

### Screenshots
Note how the AI reply has a formatted text, the code that is NOT within code blocks, should use the same font as user messages.
![image](https://github.com/user-attachments/assets/aa38a985-328f-4709-a4f6-785f1642ee5c)

**Comment by Guocork** [comment]
i fix that #267
