### ISSUE TITLE
Replace `cx.widget_action()` calls with `cx.action()` when possible

### ISSUE THREAD

**Issue by joulei** [moxin-org/moly#290]
### Context
In some parts of the codebase we are dispatching actions through `cx.widget_action(widget_uid, path, action)` where the first two arguments (widget_uid, and scope) are actually not being used anywhere where the action is being used.

For example `StoreAction::Search` is being dispatched as a `widget_action`, when it could be a simple `action`.

In `search_bar.rs`
```rs
 cx.widget_action(
    widget_uid, // this is not necessary elsewhere
    &scope.path, // this is not necessary elsewhere
    StoreAction::Search(keywords.to_string()),
);
```
The above can and should be replaced with:
```rs
cx.action(StoreAction::Search(keywords.to_string()));
```

In `app.rs` (and other files that listen to this action)
```rs
for action in actions.iter() {
    match action.as_widget_action().cast() {
        StoreAction::Search(keywords) => {
            // ...
        }
        // ...
    }
```
This should be replaced with:
```rs
for action in actions.iter() {
    match action..cast() { // remove .as_widget_action()
        StoreAction::Search(keywords) => {
            // ...
        }
        // ...
    }
```

### Approach

We should make a list of all the places in Moly where this is happening, and then refactor the code accordingly. 
It's best if we do this in separate pull requests for each type of action, so that we can easily debug if something breaks.

It's very important to make sure the `widget_uid` is not actually being used, if there is some code that listens to the action and used the widget_uid or the path, then we should keep it as `widget_action`.

**Comment by Guocork** [comment]
I think I’ve already solved this issue.

**Comment by Guocork** [comment]
I think this issue can be closed now. I've replaced all instances of `cx.widget_action() `in Moly that could be replaced.
