### ISSUE TITLE
Enhanced formats for model card design

### ISSUE THREAD

**Issue by joulei** [moxin-org/moly#309]
## Context
We want to improve the design of the chat history entries.
Currently we have this card format:

![Image](https://github.com/user-attachments/assets/275cfd62-b207-4541-b9d2-29fe21050a94)

Which we want to replace with a simpler and cleaner list:

![Image](https://github.com/user-attachments/assets/d8339a0a-a756-4d3b-bf51-852eb6bd55c2)

## Requirements:
- Only show the box outline on the currently selected chat
- Add slightly darker color on hover for the non-selected chats
- Instead of including the timestamp on each entry, group the entries based on date as shown above.
- Instead of using the raw filename like in the above screenshot, use a more readable format like we do for the downloaded files table in My Models:
![Image](https://github.com/user-attachments/assets/e1fcf77b-5303-4d0b-b66d-35d0530b469e)

### Further improvements

Currently every "profile" bubble (the rounded view with the model's first initial) for each model has the same dark blue color. We can replace this by giving each model file a different color that we can keep consistent across the app and across sessions.
One way to do this is to hash the model file name into a number, and then use that number to generate a color (this could be done in a pixel shader), and this mapping between model and color, could be cached to memory or disk. There are many ways to do this, so feel free to share suggestions.

**Comment by Guocork** [comment]
I‘ll try to enchance that.

**Comment by joulei** [comment]
@Guocork thanks! sounds like a good idea.
I can provide help with splitting the different cards between `Today`, `Yesterday`, etc.. We'll probably insert a label in the PortalList between the items. You can start with the rest first and I'll assist you there.

**Comment by Guocork** [comment]
@joulei Ok, Thank you! 
And I remember last time you were in the office, you submitted a PR to fix the issue where the DSL in Makepad couldn’t save live changes on Linux. But now, in Moly, I still need to recompile and run after modifying the layout to see the changes. I’m not sure what’s going on. If that feature were available, it would be much easier for me to fix this issue.

**Comment by joulei** [comment]
> @joulei Ok, Thank you! And I remember last time you were in the office, you submitted a PR to fix the issue where the DSL in Makepad couldn’t save live changes on Linux. But now, in Moly, I still need to recompile and run after modifying the layout to see the changes. I’m not sure what’s going on. If that feature were available, it would be much easier for me to fix this issue.

Ok, i'll see if I can replicate the issue. We definitely want DSL reloading working

**Comment by joulei** [comment]
Hi @Guocork sorry for a last minute notice but we will actually get most of these improvements out of the mofa-integration branch.
I just learned that for the agents integration with mofa, there has been some work already improving the chat history.
If you already have work in progress for this, perhaps you can leave it on hold for now and we can re-visit it after merging the mofa work.
Thanks and sorry for the inconvenience!

**Comment by joulei** [comment]
Closing this for now because we got most of these changes out of the mofa integration.
